#!/bin/sh
# chkconfig: 123456 90 10
# sneak.py - Linux command-line logger (streamline history files)
#

workdir=/usr/local/bin/sneak

start() {
    cd $workdir
    /usr/bin/python sneak.py &
    echo "sneak.py started."
}

status() {
    pid_status=$(ps aux | grep sneak.py | grep -v grep | awk '{print $2}')

    if [ -n $pid_Status ]; then
        echo "sneak.py is running"
    else
        echo "sneak.py is not running."
    fi
}

stop() {
    pid=$(ps aux | grep sneak.py | grep -v grep | awk '{print $2}')
    kill $pid
    sleep 2
    echo "sneak.py killed."
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: /etc/init.d/sneak {start|stop|restart|status}"
    exit 1
esac
exit 0
